local :
  key : application-local

common :
  common :
    key : applicationCommon
  key : common

logging:
  file:
    path: /Users/subinjang/DEV/workspace/upload/logs/wsurvey/web
    name: wsurvey-web-local