spring:
  profiles:
    group:
      develop: common,common-local,local
      quality-assurance: common, common-qas, qas
      production: common,common-prd,prd

local :
  local :
    key : application
  key : applicationkey
