spring:
  profiles:
    group:
      develop: common,common-local,local
      quality-assurance: common, common-qas, qas
      production: common,common-prd,prd
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

local :
  local :
    key : application
  key : applicationkey
#웹 서버 포트 설정
server:
  port: 9001
